[tool.ruff]

target-version = "py310"

exclude = [
	"annotator",
  "tests",
  "web_tests",
  "example",
  "extract_controlnet_diff.py",
  "scripts/movie2movie.py",
	"scripts/preprocessor/legacy/preprocessor_compiled.py",
	"scripts/preprocessor/__init__.py",
]

ignore = [
	"E501", # Line too long
	"E721", # Do not compare types, use `isinstance`
	"E731", # Do not assign a `lambda` expression, use a `def`

	"I001", # Import block is un-sorted or un-formatted
	"C901", # Function is too complex
	"C408", # Rewrite as a literal
	"W605", # invalid escape sequence, messes with some docstrings
]